name: Weekly report

on:
  schedule:
    - cron: 0 3 * * 1

jobs:
  weekly-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo ::set-env name=BRANCH_NAME::"$(date '+%F')"
          echo ::set-env name=FILE_NAME::"$(date '+%F')-one-to-one.md"
          echo ::set-env name=TITLE::"Week of $(date '+%d %B %Y')"
          echo ::set-env name=MANAGER_GITHUB_USERNAME::"TODO"
          echo ::set-env name=REPORT_GITHUB_USERNAME::"TODO"

      - name: Create new notes template file
        run: |
          cp meeting-notes/templates/one-to-one.md "meeting-notes/$FILE_NAME"
          sed -i "" "s~{{TITLE}}~$TITLE~g" "meeting-notes/$FILE_NAME"

      - name: Commit and push notes template file to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
          git config --global user.name $GITHUB_ACTOR
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Create a meeting notes template"
          git push --force --set-upstream "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" $BRANCH_NAME

      - name: Open pull request
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const createPull = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: process.env.TITLE,
              body: "Add any notes for the 1:1",
              head: process.env.BRANCH_NAME,
              base: "master",
            });

            await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: createPull.data.number,
              assignees: [
                process.env.MANAGER_GITHUB_USERNAME,
                process.env.REPORT_GITHUB_USERNAME
              ],
            });
